export const PRODUCTS_REQ = "GETSPRODUCTSREQ";
export const PRODUCTS_SUCCESS = "PRODUCTSSUCCESS";
export const PRODUCTS_FAILURE = "PRODUCTSFAILURE";
export const PRODUCTS_DATA = "PRODUCTSDATA";
export const PRODUCTS_SORT = "SORTPRODUCTS";